"""Add force_2fa_setup to admin_users

Revision ID: 80ff8f0d7544
Revises: 0003_gamification_and_antifraud
Create Date: 2026-03-06 11:19:03.161476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ff8f0d7544'
down_revision: Union[str, None] = '0003_gamification_and_antifraud'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('force_2fa_setup', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'force_2fa_setup')
    # ### end Alembic commands ###
